# Generated by Django 3.2.5 on 2021-08-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
    ]
