# Generated by Django 3.2.8 on 2022-01-01 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishList',
            field=models.ManyToManyField(related_name='WishList', to=settings.AUTH_USER_MODEL),
        ),
    ]
