# Generated by Django 3.2.5 on 2021-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='image2',
            new_name='bannerImage',
        ),
        migrations.AddField(
            model_name='media',
            name='image5',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, default='Pakistan', max_length=200, null=True),
        ),
    ]
