# Generated by Django 3.1.4 on 2022-02-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220216_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerImage', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
            ],
        ),
    ]
